# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordToGeom
                                 A QGIS plugin
 Create geometries from coordinates
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-01
        copyright            : (C) 2024 by ELFADILY GEOCONSEIL
        email                : elfadily.igt@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


def classFactory(iface):
    """Load CoordToGeom class from file coord_to_geom.
    
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .coord_to_geom import CoordToGeomPlugin
    return CoordToGeomPlugin(iface)